In [1]:
import tensorflow as tf
print(tf.__version__)

2.14.0


In [2]:
import numpy as np
print(np.__version__)

1.26.4


In [3]:
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

model = Sequential()
model.add(layers.Input(shape=(4,))) # 열 4개
model.add(layers.Dense(50, activation='sigmoid')) # uniform: , 뉴련의 갯수 : 50
model.add(layers.Dense(30, activation='sigmoid'))
model.add(layers.Dense(3, activation='softmax'))
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense (Dense)               (None, 50)                250       
                                                                 
 dense_1 (Dense)             (None, 30)                1530      
                                                                 
 dense_2 (Dense)             (None, 3)                 93        
                                                                 
Total params: 1873 (7.32 KB)
Trainable params: 1873 (7.32 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [5]:
# 훈련 정의함
model.compile(optimizer='adam', loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

In [7]:
from sklearn import datasets
iris = datasets.load_iris()
iris_X = iris.data
iris_y = iris.target

In [8]:
from sklearn.model_selection import train_test_split
train_X, test_X, train_y, test_y = train_test_split(iris_X, iris_y)

In [9]:
model.fit(train_X, train_y, epochs=100)

Epoch 1/100
4/4 [==============================] - 1s 3ms/step - loss: 1.2423 - accuracy: 0.1161
Epoch 2/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1861 - accuracy: 0.2500
Epoch 3/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1428 - accuracy: 0.3482
Epoch 4/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1150 - accuracy: 0.3482
Epoch 5/100
4/4 [==============================] - 0s 2ms/step - loss: 1.1050 - accuracy: 0.3482
Epoch 6/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0930 - accuracy: 0.3571
Epoch 7/100
4/4 [==============================] - 0s 7ms/step - loss: 1.0873 - accuracy: 0.5357
Epoch 8/100
4/4 [==============================] - 0s 3ms/step - loss: 1.0812 - accuracy: 0.3393
Epoch 9/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0742 - accuracy: 0.5000
Epoch 10/100
4/4 [==============================] - 0s 2ms/step - loss: 1.0661 - accuracy: 0.6786
Epoch 11/100
4/4 [===========

In [10]:
model.evaluate(test_X, test_y)

2/2 [==============================] - 0s 3ms/step - loss: 0.3492 - accuracy: 0.9211


[0.34922218322753906, 0.9210526347160339]

In [11]:
pred = model.predict(test_X)

2/2 [==============================] - 0s 2ms/step


In [12]:
print(pred)

[[0.00871317 0.39609638 0.5951904 ]
 [0.92323273 0.0717031  0.00506415]
 [0.00392276 0.28295276 0.71312445]
 [0.00369557 0.27996156 0.71634287]
 [0.95158726 0.04510108 0.00331168]
 [0.00357526 0.2735005  0.72292423]
 [0.02473108 0.55446255 0.42080632]
 [0.94556123 0.05076113 0.00367756]
 [0.94021916 0.05576579 0.00401502]
 [0.9257876  0.06930573 0.00490657]
 [0.03322063 0.60008246 0.3666969 ]
 [0.90311784 0.09047557 0.00640667]
 [0.00287854 0.24654971 0.7505717 ]
 [0.07611018 0.67980236 0.24408741]
 [0.9539307  0.04288302 0.00318629]
 [0.01204445 0.44481826 0.5431374 ]
 [0.03522092 0.5995073  0.36527175]
 [0.00237365 0.22767524 0.7699511 ]
 [0.02316828 0.5469289  0.42990285]
 [0.93522537 0.06045661 0.00431797]
 [0.9213072  0.07350219 0.00519055]
 [0.0304674  0.5867435  0.38278913]
 [0.00256241 0.23590003 0.76153755]
 [0.01066253 0.42986876 0.5594686 ]
 [0.9279607  0.06727719 0.0047622 ]
 [0.01133581 0.4394878  0.54917645]
 [0.00320315 0.25916427 0.7376325 ]
 [0.05263239 0.64868486 0.29

In [13]:
print(type(pred))

<class 'numpy.ndarray'>


In [14]:
print(np.argmax(pred, axis=1))

[2 0 2 2 0 2 1 0 0 0 1 0 2 1 0 2 1 2 1 0 0 1 2 2 0 2 2 1 0 1 2 1 0 2 1 1 1
 2]


In [15]:
print(test_y)

[2 0 2 2 0 2 1 0 0 0 1 0 2 1 0 1 1 2 1 0 0 1 2 2 0 1 2 1 0 1 2 1 0 2 1 1 1
 1]
